### ISSUE TITLE
bug (probably from ArcGis side)

### ISSUE THREAD

**Issue by cecilesauder** [benyamindsmith/mapBliss#1]
Hi,
I have a bug testing your example :/

I'm going to nvestigate on the side of the problems between ArcGis and Ubuntu but if you have an idea to know where this bug comes from...

![mapbliss_bug](https://user-images.githubusercontent.com/7116394/198689623-b7af7d0b-8ae7-4f25-bf50-d0780bff79a3.png)

Well, I don't have any problems with `plot_city_view()` and with `plot_flights()`, but running `plot_route()` I have the same error message.

So I test alone some functions used in `plot_route()` : 
- `geocode(), osrmRoute(), st_geometry(), leaflet()`  : and  they work ...

I isolate the problem and it comes from the for loop : 
`
for(i in 1:(nrow(address_single)-1)){
  trip[[i]] <- osrmRoute(src=address_single[i,2:3] %>% c,
                         dst=address_single[i+1,2:3] %>% c,
                         returnclass="sf",
                         overview="full",
                         osrm.profile = how[i] )
}
`

**Comment by benyamindsmith** [comment]
Hmm interesting. 

I am going to update my local packages and see if I can simulate the error. You're the second person to point this out. I will look into it and get back to you on it!

Thank you for trying the package out and finding this issue!

**Comment by cecilesauder** [comment]
I found ! 
The `src` parameter in `osrmRoute` has to be a vector and `%>% c` return a list so with `%>% unlist` after, it works 

(and the same for `dst` parameter)

![Capture d’écran du 2022-10-28 19-46-45](https://user-images.githubusercontent.com/7116394/198700064-83410dc6-59a6-4ac8-97c6-67708ebaf9d2.png)

Sorry for my very untidy debugging :'D

**Comment by benyamindsmith** [comment]
@cecilesauder send a PR!
