### ISSUE TITLE
plot[_hybrid]_route_flex: label positioning

### ISSUE THREAD

**Issue by shaggycamel** [benyamindsmith/mapBliss#11]
Hey Ben, great package!

I've noticed the `label_position` argument doesn't place labels in their designated spots, they all default to "left".
This is happening in both the `plot_route_flex` & `plot_hybrid_route_flex` functions.

In the past label positioning did work in these functions, I can't pinpoint exactly what changed on my machine and when positioning stopped working, apologies.

I've attached my OS & R configuration, hope it's helpful (this is my first time raising an issue in the public domain - no idea what i'm doing). Let me know if you need any more info.

[os_info.txt](https://github.com/benyamindsmith/mapBliss/files/10525806/os_info.txt)
[r_info.txt](https://github.com/benyamindsmith/mapBliss/files/10525807/r_info.txt)

Cheers,
Oliver

**Comment by benyamindsmith** [comment]
@shaggycamel Thank you! I'm flattered to see that you are using it!

Would you mind putting together a reproducible example so I can see the problem?

**Comment by shaggycamel** [comment]
Thanks for responding @benyamindsmith :)
I've figured it out, for some reason leaflet doesn't like named vectors. Here's a snippet of my code:


```
library(mapBliss)
library(purrr)

destinations <- list(
 "Cairo" = c(transport=NA_character_, label_pos="top"),
  "Luxor" = c(transport="car", label_pos="right"), 
  "Aswan" = c(transport="car", label_pos="bottom"), 
  "Kharga Oasis" = c(transport="car", label_pos="left")
)

plot_hybrid_route_flex(
  names(destinations), 
  how = na.omit(map_chr(destinations, "transport")), 
  label_position = map_chr(destinations, "label_pos") 
)
```

The fix was to wrap the `map_chr()` functions within `as.vector()`, so vector elements lost their name. No idea why, but that seemed to do the trick.

**Comment by benyamindsmith** [comment]
Hmm. I don't know if I should have this as a feature or just leave this as the way `mapBliss` works. It definitely looks cleaner but might not be intuitive to do for less experienced R programmers.

Looks like a great road trip though!
![image](https://user-images.githubusercontent.com/46410142/215496264-39b7bde9-6f2f-49f9-b2cd-1e6b115c6b77.png)

**Comment by shaggycamel** [comment]
Yep, I agree. We're getting into the philosophical side of package/code structure.
This ticket can be closed now, btw. It was nice talking R with ya :)

**Comment by benyamindsmith** [comment]
My pleasure! Feel free to join the R discord server also!  https://discord.gg/uaVEkXx8
