### ISSUE TITLE
No label indentation if label_position="left"

### ISSUE THREAD

**Issue by GTBoon72** [benyamindsmith/mapBliss#4]
Also tried:
- text_indent, but didn't see any effect
- adding spaces to label_text, but that is effectively ignored

**Comment by benyamindsmith** [comment]
Thank you for checking out the package!

Would you mind sharing your code example so I can see?

**Comment by GTBoon72** [comment]
You can see the difference in spacing with below code example, switching between "left" and "right". Using "right", there's at least one character of space between the marker and the label, whereas using "left", there's not a millimeter space.
plot_hybrid_route(addresses=c("Amsterdam","Berlijn","Amsterdam"), 
                  how=c("car","flight","car"), 
                  weight=3,
                  colour="red",
                  label_position = "left",
                  mapBoxTemplate="//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
)

**Comment by benyamindsmith** [comment]
@GTBoon72 I looked into the issue, what you need to do is change the `text_indent` argument from being positive to negative. 
```r
plot_hybrid_route(addresses=c("Amsterdam","Berlijn","Amsterdam"),
                  how=c("car","flight","car"),
                  weight=3,
                  colour="red",
                  label_position = "left",
                  mapBoxTemplate="//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                  text_indent = "-100px"
)
```
Let me know if this works for you also. 

Source: https://stackoverflow.com/a/22066114/7058869

**Comment by GTBoon72** [comment]
Thanks for looking into this. Using text_indent with negative value does indeed sort effect. 
However, with different length of labels, it works a bit unexpectedly. For example, see the results of the below snippet. Amsterdam is printed near the marker, London is far off, and Newcastle hasn't yet shifted at all. This is probably because the length of the first, or the longest string, is used as a reference. This could easily be fixed by introducing & passing-through the CSS property text-align. But I suppose that is more of a feature request than an Issue :-)
plot_hybrid_route(addresses=c("Amsterdam","London","Newcastle upon Tyne"), 
                  how=c("car","car","car"), 
                  weight=3,
                  colour="red",
                  label_position = "left",
                  text_indent= "-8em",
                  mapBoxTemplate="//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
)

**Comment by benyamindsmith** [comment]
@GTBoon72  This is what I've come up with. Is this what you are looking to do? 

```r
library(leaflet)
library(osrm)
library(tidygeocoder)
library(geosphere)
library(tidyverse)
library(purrr)
library(sf)

plot_hybrid_route<- function(addresses,
                             how=c("car","flight","bike","foot"),
                             colour="black",
                             opacity=1,
                             weight=1,
                             radius=2,
                             label_text=addresses,
                             label_position="bottom",
                             font = "Lucida Console",
                             font_weight="bold",
                             font_size= "14px",
                             text_indent=c("15px","15px"),
                             mapBoxTemplate= "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                             nCurves=100,
                             zoomControl=c(0.1,0.1,-0.1,-0.1)){
  
  address_single <- tibble(singlelineaddress = addresses) %>%
    geocode(address=singlelineaddress,method = 'arcgis') %>%
    transmute(id = singlelineaddress,
              lon=long,
              lat=lat)
  
  trip <- matrix(nrow=1,ncol=2)
  
  
  for(i in 1:(nrow(address_single)-1)){
    if(how[i]=="flight"){
      trip<-rbind(trip,
                  gcIntermediate(address_single[i,2:3],
                                 address_single[i+1,2:3],
                                 n=nCurves,
                                 addStartEnd = T) )
    }else{
      roadTrip<-osrmRoute(src=address_single[i,2:3] %>% c  %>% unlist,
                          dst=address_single[i+1,2:3] %>% c  %>% unlist,
                          returnclass="sf",
                          overview="full",
                          osrm.profile = how[i])
      
      
      roadTrip<- do.call(rbind,st_geometry(roadTrip)) %>%
        as_tibble(.name_repair = "unique") %>%
        set_names(c("lon","lat")) %>%
        as.data.frame() %>%
        as.matrix()
      
      trip <- rbind(trip,
                    roadTrip)
    }
    
  }
  
  
  m<-leaflet(trip,
             options = leafletOptions(zoomControl = FALSE,
                                      attributionControl=FALSE)) %>%
    fitBounds(lng1 = max(address_single$lon)+zoomControl[1],
              lat1 = max(address_single$lat)+zoomControl[2],
              lng2 = min(address_single$lon)+zoomControl[3],
              lat2 = min(address_single$lat)+zoomControl[4]) %>%
    addTiles(urlTemplate = mapBoxTemplate) %>%
    addCircleMarkers(lat = address_single$lat,
                     lng = address_single$lon,
                     color = colour,
                     stroke = TRUE,
                     radius = radius,
                     fillOpacity = opacity) %>%
    addPolylines(lng=trip[,1],
                 lat=trip[,2],
                 color = colour,
                 opacity=opacity,
                 weight=weight) 
  
  for(i in 1:nrow(address_single)){
    
    m<-m %>%
      addLabelOnlyMarkers(address_single$lon[i],
                          address_single$lat[i],
                          label =  label_text[i],
                          labelOptions = labelOptions(noHide = T,
                                                      #direction = label_position,
                                                      textOnly = T,
                                                      style=list("font-family" = font,
                                                                 "font-weight"= font_weight,
                                                                 "font-size"=font_size,
                                                                 "text-indent"=text_indent[i],
                                                                 "text-align"=label_position[i])))
  }
  
  m
}

# New approach
viz_1<-plot_hybrid_route(addresses=c("Amsterdam","London","Newcastle upon Tyne"),
                  how=c("car","car"),
                  weight=3,
                  colour="red",
                  label_position = c("left","left","left"),
                  text_indent= c("-6em","-5em","-13em"),
                  mapBoxTemplate="//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
)


viz_1
```
![image](https://user-images.githubusercontent.com/46410142/199320547-a10fdcc9-48c2-4dde-b276-435107abc262.png)

Compared to the old approach: 

``` r

# Old approach

viz_2<-mapBliss::plot_hybrid_route(addresses=c("Amsterdam","London","Newcastle upon Tyne"),
                            how=c("car","car"),
                            weight=3,
                            colour="red",
                            label_position = "left",
                            text_indent= "-8em",
                            mapBoxTemplate="//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
)

viz_2

```
![image](https://user-images.githubusercontent.com/46410142/199320770-32c917c0-fcb7-412c-9f30-ecff98194e7f.png)

**Comment by benyamindsmith** [comment]
The above code is an improvement but will need the other plot functions to also be updated accordingly with documentation. The README.md also needs work. So far the [blog](https://bensstats.wordpress.com/2022/10/28/robservations-40-packaging-my-route-map-code-introducting-mapbliss/) is the most accurate portrayal of what the functions do. Maybe I'll rename them as depreciated or call these new functions "flex functions" `plot_route_flex()`,`plot_flight_flex()`, `plot_hybrid_route_flex()`.

What do you think?

**Comment by GTBoon72** [comment]
Making the indent and position configurable per label is definitely a great enhancement. In my fork, I was experimenting with padding as well, but I think your approach is way more flexible. 

From acceptance point of view, you could consider using a git tag with a version number, rather than renaming or deprecating the functions. In your blog you can refer to this tag/version, and continue coding enhancements.

**Comment by GTBoon72** [comment]
Did some more experimenting, and ended up with this:

                          labelOptions = labelOptions(noHide = T,
                                                      direction = label_position[i],
                                                      textOnly = T,
                                                      style=list("font-family" = font,
                                                                 "font-weight"= font_weight,
                                                                 "font-size"= font_size,
                                                                 "padding" = text_indent[i]
                                                                 ))

**Comment by benyamindsmith** [comment]
@GTBoon72  Hmm. I think I'm going to make them `_flex()` functions. They can be used for more flexible versions of the original plotting with the features discussed plus any new features that would be desired. 

They would be named:

1. `plot_route_flex()`
2. `plot_flight_flex()`
3. `plot_hybrid_route_flex()`

Coding them wouldn't be too much work. The documentation part is the headache. 

If you want to make them and submit a PR let me know, if not then I'll try to start working on them when I get time!

**Comment by benyamindsmith** [comment]
@GTBoon72 added the `_flex()` functions which have the functionality that is desired.

I need to fix up documentation but otherwise its good to go.

**Comment by GTBoon72** [comment]
Good progress! In the current version of the package, only the plot_route_flex function is available, probably because the function names haven't changed in the other _flex.R files.

**Comment by benyamindsmith** [comment]
@GTBoon72  good catch! I just updated that. Now to deal with the daunting task of documentation.

**Comment by GTBoon72** [comment]
Very nice, I like the results a lot!
Here's my picture, created with this call:
plot_hybrid_route_flex(addresses=c("Amsterdam","Freddrikshavn","Kristiansand","Oslo"), 
                  how=c("car","flight","car"), 
                  weight=3,
                  colour="red",
                  label_position = c("left", "right","left","top"),
                  text_indent= c("1em","1em","1em","0.5em"),
                  mapBoxTemplate="https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg"
)

![Rplot](https://user-images.githubusercontent.com/7267155/199765335-5ec79f81-556d-42bd-a443-49ea29145208.jpeg)
